---
- name: Copy and unpack Hadoop
  unarchive:
    src: "{{package_home}}/{{hadoop_archive}}"
    dest: "/opt"
- name: Configure core-site.xml
  template:
    src: core-site.xml.j2
    dest: "{{hadoop_home}}/etc/hadoop/core-site.xml"
- name: Configure hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: "{{hadoop_home}}/etc/hadoop/hdfs-site.xml"
- name: Configure slaves
  template:
    src: slaves.j2
    dest: "{{hadoop_home}}/etc/hadoop/slaves"

