- name: format-namenode
  hosts: namenode
  become: yes

  environment:
    JAVA_HOME: "{{java_home}}"

  tasks:
    - name: Format namenode
      command: "{{hadoop_home}}/bin/hdfs namenode -format"
